theme: jekyll-theme-cayman
# theme: jekyll-theme-hacker
title: WTF
description: "\"And now, I'm going down to Emmett's Fix-It Shop. [cocks gun] To fix...Emmett.\""
page_excerpts: true
lang: en-AU
google_analytics: G-29R261QM9P
plugins:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter
  - jekyll-sitemap
whitelist:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter