# theme: jekyll-theme-cayman
theme: jekyll-theme-hacker
title: WTF
description: "\"And now, I'm going down to Emmett's Fix-It Shop. [cocks gun] To fix...Emmett.\""
page_excerpts: true
plugins:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter
whitelist:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter