theme: jekyll-theme-cayman
# theme: jekyll-theme-hacker
title: WTF
description: "\"And now, I'm going down to Emmett's Fix-It Shop. [cocks gun] To fix...Emmett.\""
page_excerpts: true
lang: en-AU
google_analytics: G-29R261QM9P
repository: tlourey/tlourey.github.io
url: https://tlourey.github.io
# markdown: GFM
markdown: kramdown
# collections:
  # - category
    # output: true
  # - categories
plugins:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter
  - jekyll-sitemap
  - jekyll-feed
whitelist:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
relative_links:
  # enabled: true # already enabled by default
  collections: true